# Generated by Django 4.2.6 on 2024-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='./main_page/social_media/', verbose_name='Иконка соцсети')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка')),
                ('first_btn', models.CharField(max_length=100, verbose_name='Текст на первой кнопке')),
                ('second_btn', models.CharField(max_length=100, verbose_name='Текст на второй кнопке')),
                ('third_btn', models.CharField(max_length=100, verbose_name='Текст на третьей кнопке')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='./main_page/social_media/', verbose_name='Иконка соцсети')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка на соцсеть')),
            ],
        ),
    ]
