# Generated by Django 4.2.6 on 2024-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='first_btn_lat',
            field=models.CharField(default='', max_length=100, verbose_name='Текст на первой кнопке на латинице'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='second_btn_lat',
            field=models.CharField(default='', max_length=100, verbose_name='Текст на второй кнопке на латинице'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='third_btn_lat',
            field=models.CharField(default='', max_length=100, verbose_name='Текст на третьей кнопке на латинице'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./main_page/social_media/', verbose_name='Картинка на главной странице'),
        ),
    ]
