# Generated by Django 4.2.6 on 2023-11-19 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_clientdevice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientdevice',
            unique_together={('user', 'device_id')},
        ),
    ]
