# Generated by Django 4.2.6 on 2024-09-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('client', '0006_alter_client_options_alter_clientdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subscriptiontype'),
        ),
    ]
