# Generated by Django 4.2.6 on 2024-09-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='subscription',
            new_name='subscription_type',
        ),
    ]
