# Generated by Django 4.2.6 on 2024-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_wrapper',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
