# Generated by Django 4.2.6 on 2024-09-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_youtube_link_post_youtube_wrapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_ru',
            new_name='content_latin',
        ),
    ]
