# Generated by Django 4.2.6 on 2024-09-03 19:16

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_latin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название на латыни'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_latin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название на латыни'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_latin',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент на латыни'),
        ),
    ]
