# Generated by Django 4.2.6 on 2024-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_category_name_latin_post_name_latin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
