# Generated by Django 4.2.6 on 2024-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_category_slug_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_lat',
        ),
        migrations.AddField(
            model_name='post',
            name='slug_lat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
