# Generated by Django 4.2.6 on 2024-09-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_category_slug_lat_post_slug_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtube_wrapper',
        ),
    ]
