# Generated by Django 4.2.6 on 2024-09-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_youtube_link_remove_post_youtube_wrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_lat',
            field=models.CharField(blank=True, default='', editable=False, max_length=256, null=True),
        ),
    ]
