# Generated by Django 4.2.6 on 2024-09-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_post',
            field=models.OneToOneField(blank=True, limit_choices_to={'category': models.CharField(max_length=256, verbose_name='Название')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_in_category', to='post.post'),
        ),
    ]
