# Generated by Django 4.2.6 on 2024-09-15 16:40

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_category_main_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_post',
            field=models.OneToOneField(blank=True, limit_choices_to={'category': builtins.id}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_in_category', to='post.post'),
        ),
    ]
